version: '3.8'

# Simple docker-compose for frontend only
# Backend runs separately: docker run -d --name backend -p 8080:8080 checkin-backend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: checkin-frontend:latest
    container_name: checkin-frontend
    ports:
      - "3001:80"  # Map to port 3001 to avoid conflicts
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3