services:
  checkin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: checkin-frontend:latest
    container_name: checkin-frontend
    ports:
      - "3000:80"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s